### ISSUE TITLE
Support for N=2048

### ISSUE THREAD

**Issue by RasoulAM** [tuneinsight/lattigo#158]
Is there a plan to add N=2048 to the set of parameters?
Is there a specific reason that it is not supported at the moment?

**Comment by Pro7ech** [comment]
Hi RasouIAM, 

Although there aren't default parameters for this ring degree, you can create custom parameters with N=2048, but in the current state of the library you must specify a modulus for P, which, for small parameters, can be prohibitive since Q is already very small. Eventually being able to create parameters with an empty P will be added in master (it's in the branch dev_RGSW).
