### ISSUE TITLE
Questions about decomposition in key-switching operation in CKKS

### ISSUE THREAD

**Issue by bluefrogGG** [tuneinsight/lattigo#185]
I have a question regarding the key-switching operation in CKKS, especially about decomposition. 
lattigo supports multiple numbers of alpha and it is said to follow the implementation proposed in the paper from Han and Ki [1] from [2]. From the paper [1], decomposition must include zero-padding and splitting (shown in the figure), where each polynomial in each level must be pumped up by [Q']_(q_(ja+i)).  I have carefully looked over the functions `SwitchKeysInPlaceModDown`, `DecomposeSingleNTT`, `DecomposeAndSplit`, and the others related, but I have failed in finding such step in the current implementation. 

I am not sure whether the algorithm is slightly modified so that such operation is not required, or it is hidden in the other operations. I would really appreciate any help.

Thanks in advance.

![image](https://user-images.githubusercontent.com/30410207/157187198-5d17d233-dcac-4ffd-9aef-63ae40740746.png)

References
[1] Han, Kyoohyung, and Dohyeong Ki. "Better bootstrapping for approximate homomorphic encryption." Cryptographers’ Track at the RSA Conference. Springer, Cham, 2020.
[2] Bossuat, Jean-Philippe, et al. "Efficient bootstrapping for approximate homomorphic encryption with non-sparse keys." Annual International Conference on the Theory and Applications of Cryptographic Techniques. Springer, Cham, 2021.

**Comment by Pro7ech** [comment]
You are correct, in practice there is no need for padding and one can directly carry out the key-switch at the level of the ciphertext by ignoring the unused moduli of the switching key (the ones that are not anymore used by the ciphertext at lower level).

The algorithm is however, as pointed out in our paper, slightly modified with respect to the one of Han and Ki because we include the entire RNS power basis in the key instead of only part of it and multiplying the ciphertext before the key switch.
