### ISSUE TITLE
Curious about ckks/bridge.go and conjugate-invariant ring 

### ISSUE THREAD

**Issue by lr555** [tuneinsight/lattigo#201]
Hello, I find that lattigo adds conjugate-invariant ring and the switching between the standard CKKS and the conjugate invariant variant of CKKS (ckks/bridge.go).
     So how the switching is achieved and what is the difference between conjugate-invariant ring and the standard CKKS in homomorphic operations (add, sub, mult)?

**Comment by Pro7ech** [comment]
The Conjugate-Invariant ring is the sub-ring Z[X+X^-1] of Z[X], so the bridge is simply carried out using key-switching.

There is no difference between the two schemes regarding homomorphic operations, are exactly the same (the Conjugate-Invariant ring is embedded in the regular ring), except that only N/2 coefficients are sufficient to work in the Conjugate-Invariant ring, due to its structure, which enables a much more efficient implementation. The main difference is that the Conjugate-Invariante ring requires a special NTT that is slightly more expensive than the regular one (it requires an additional constant multiplication).

**Comment by lr555** [comment]
Thanks for your help!

**Comment by lr555** [comment]
Sorry to bother you, I read the paper “Approximate Homomorphic Encryption over the Conjugate-invariant Ring”.
Is the embedding you mentioned in "the Conjugate-Invariant ring is embedded in the regular ring" in lattigo the same as the following method?
![image](https://user-images.githubusercontent.com/26160793/166092305-0c3e8386-7520-49c6-aae7-77f6297b3ff7.png)

> The Conjugate-Invariant ring is the sub-ring Z[X+X^-1] of Z[X], so the bridge is simply carried out using key-switching.
> 
> There is no difference between the two schemes regarding homomorphic operations, are exactly the same (the Conjugate-Invariant ring is embedded in the regular ring), except that only N/2 coefficients are sufficient to work in the Conjugate-Invariant ring, due to its structure, which enables a much more efficient implementation. The main implementation difference is that the Conjugate-Invariante ring requires a special NTT that is slightly more expensive than the regular one (it requires an additional constant multiplication).

**Comment by lr555** [comment]
Sorry for forgetting to reopen the issue.

Thanks for your help!
