### ISSUE TITLE
Accessing and decrypting individual elements of the array

### ISSUE THREAD

**Issue by cutukmirza** [tuneinsight/lattigo#208]
Is it possible to access and decrypt just a single element of the encrypted array?

Example:
data := [5]uint64{1, 2, 3, 4, 5}
p1 := encoder.EncodeNew(data, params.MaxLevel(), params.DefaultScale(), params.LogSlots())
c1 := encryptor.EncryptNew(p1)

and then access and decrypt, for example, 1st or 3rd element of encrypted data.

**Comment by Pro7ech** [comment]
Unfortunately this is not possible since the encoder needs all the 2^params.LogSlots() coefficients to be able to decode the plaintext (part of the encoding and decoding are FFT). 

However, what you could do is homomorphically mask your values with a plaintext encoding a binary vector, which will return a ciphertext with only the selected elements.

**Comment by cutukmirza** [comment]
Thank you! I'll give the binary vector suggestion a go :)
