### ISSUE TITLE
Working of the dynamic access structure

### ISSUE THREAD

**Issue by aasimmd** [tuneinsight/lattigo#216]
In the paper : _Multiparty Homomorphic Encryption from Ring-Learning-with-Errors_, there is mention of Dynamic access structure. I am confused about how it works and what exactly to do in the case of parties leaving and joining. It would be very helpful if there is more detailed explanation on how it works/how to implement it.

**Comment by ChristianMct** [comment]
The basic idea for implementing dynamic access-structures is to re-encrypt ciphertexts to be "transferred" from the previous set of party P to the new set of party P'.
- In general, the approach is to 1) update the collective public-key by adding the joining parties' shares and removing the leaving parties' ones, then to 2) re-encrypt the ciphertexts to be transferred to the updated key (using `PCKSProtocol`).
- In the special case where there are on leaving parties,  these departing parties can simply issue decryption shares for the ciphertexts they wish to "transfer" to the set of staying parties (using `CKSProtocol`). This is more efficient than the general approach as the staying parties do not have to produce re-encryption shares.

Note: Evaluation keys can be updated in the same way as the collective public key, except for the relinearization key which need to be regenerated. Also, regarding the implementation, we don't really have API methods to update the key structs directly. However, since it consist only in adding/subtracting shares from the arriving/departing parties from `PublicKey.Value[0]`, it should be pretty straightforward to implement.
