### ISSUE TITLE
Questions about decomposition optimization

### ISSUE THREAD

**Issue by TakanoriC** [tuneinsight/lattigo#221]
In the function `DecomposeSingleNTT` in [keyswitch.go](https://github.com/tuneinsight/lattigo/blob/master/rlwe/keyswitch.go), part of the fast basis conversion is saved because the coefficients are exactly the ones being decomposed. I think that is why the coefficients within the interval `[p0idxst, p0idxed)` can be directly copied.
![image](https://user-images.githubusercontent.com/78681506/178946055-3314aba4-a31e-4fa9-ae2d-da33d9eb0bd2.png)

My question is that why `p0idxed` equals `p0idxst+1` instead of `(beta+1)*(levelP+1)`. In my opinion, the size of the decomposition interval is greater than or equal to 1.  If `levelP>0`, there should be more than one NTT that can be saved, i.e., `min(levelP+1, levelQ+1-p0idxst)`.

A similar issue is in the function `DecomposeAndSplit` in [ring_basis_extension.go](https://github.com/tuneinsight/lattigo/blob/master/ring/ring_basis_extension.go). The multSum operations for the coefficients of `Qi` are split into two parts.  However, in this function, `lvlQStart` equals `alpha*beta`, making the split meaningless. It seems that in the second loop, `j` should start from `alpha*beta+decompLvl+2` to skip the decomposed coefficients and save more operations.
![image](https://user-images.githubusercontent.com/78681506/178945961-c88c789f-69bc-4e82-b7a8-a410fdc9a548.png)

Although the issues mentioned above do not affect correctness, I want to confirm whether my assumptions are correct, or why these optimizations are not implemented.

Thank you very much.

**Comment by Pro7ech** [comment]
You are correct, `p0idxst` and  `p0idxed` should be initialized as:

```
p0idxst := beta * (levelP + 1)
p0idxed := p0idxst  + levelP + 1
```
And indeed, the two loops could be merged. However, I think I actually forgot to finish this step, and left this as a placeholder. The reason is that the coefficients between `p0idxst` and `p0idxed` of this step can simply be copied and do not need to be calculated from the RNS reconstruction (`multsum`).

I'll add these two corrections in the dev_RGSW branch, which will soon be merged.

Thank you very much for finding these :)

**Comment by TakanoriC** [comment]
Thanks for your reply! It solved my questions.
