### ISSUE TITLE
params meaning

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#238]
Hi,
![image](https://user-images.githubusercontent.com/754293/184884718-4e81c0d8-dba7-4dfb-9032-835302047a7d.png)

I've seen CKKS parameters: logN = 14, logSlots = 13, logQP = 425, levels = 8, scale= 1099511627776.000000, sigma = 3.200000.
What do they mean in detail, e.g. any comments for them? Do they have any relations?
Like logN is a fixed 2 times logSlots? Do logQP and scale have any relations? or just ramdom value?

BR

**Comment by Pro7ech** [comment]
@macknight These are the standard cryptographic parameters of the Ring Learning with Error based CKKS scheme. The ring is Z_{QP}[X]/(X^{N}+1), and the parameters affecting the security are LogN (the log in base 2 of the ring degree), LogQP (the log in base 2 of the modulus), the distribution of the secret (by default uniform ternary) and the standard deviation of the error (here sigma). The other parameters, LogSlots (the log in base 2 of the number of plaintext slots) and scale (the integer by which values are scaled during encoding) do not affect the security but will affect, mostly, the precision of your computation. 

I cannot go into more details because the security and parameterization of R-LWE schemes is a non trivial topic that requires deep knowledge of the scheme. 

For more information about the parameterization of R-LWE based schemes and its security, I will refer you to the [homomorphic standard](https://homomorphicencryption.org/standard/)

If you want to know more about the CKKS scheme specifically you can take a lookt at the [original paper](https://eprint.iacr.org/2016/421) and its [full-RNS variant](https://eprint.iacr.org/2018/931), which is the one on which Lattigo is based.

In the mean time, you can use the default parameters as they ensure a security of 128-bit.

**Comment by macknight** [comment]
> 

Thank you for your excellent answer.

And I have some other questions:
1. How about the param "levels"? Is it a security param or precision param?
2. What is "the distribution of the secret" param? Is it the param "levels"?
3. Does these params(3 secrutiy params and 2 precision params) have relations when setting them?
like do LogN and LogSlots have this fixed relation of "LogN=LogSlots + 1"?
could I set LogN=14 while LogSlots=10? Or could I set LogN=10, LogSlots=15?
Or just LogN and LogSlots are random integers between (1, 100)?
4.For the default parameters, how to compute out the a security bit is 128-bit? 
And if I want to use default params, I just don't set them so that they use default params?
5.in this link, https://github.com/tuneinsight/lattigo/tree/master/ckks
there seems to only have 4 params: LogN, LogQ, sigma and scale. Why the example have more params?
![image](https://user-images.githubusercontent.com/754293/185020778-59c146d1-d08d-4beb-a742-5aca6a45bc42.png)
6.For logN, https://github.com/tuneinsight/lattigo/tree/master/ckks, it says "security increases with N and performance decreases with N", so why? Any simple and intuitive answer?
7. For logQ, https://github.com/tuneinsight/lattigo/tree/master/ckks, it says "(for a fixed N, a larger Q  implies both lower security and lower performance)." Why is it? Any simple and intuitive answer?


BR

**Comment by macknight** [comment]
How to change the default uniform ternary "the distribution of the secret" param? 

And is it the param "levels"? It should be a different param from "the distribution of the secret", right? Then How to set the "levels" param? Simply by setting Q or LogQ to imply "levels" param?

BR

**Comment by Pro7ech** [comment]
By default `H=0` and this will generate the secret with coefficients uniformly distributed in [-1, 0, 1]. So the expected Hamming Weight will be 2N/3. You can change H to a fixed value, for example `H=256`, this will instead generate a secret that has exactly 256 non zero coefficients [-1, 1]. But this will change the security. Only do that if you are perfectly aware of the implications. If you want to estimate the security of a R-LWE instance, you can go there -> https://github.com/malb/lattice-estimator
