### ISSUE TITLE
dbfv psi limitation issue

### ISSUE THREAD

**Issue by macknight** [tuneinsight/lattigo#269]
Hi,
![image](https://user-images.githubusercontent.com/754293/189623378-140ebd2e-040e-4832-8be2-729db4c41eb9.png)
Largest for n=8192: 512 parties, here, does it mean the code allow maximum 512 parties, and for each party's vector it has maximum 8192 elements?

And how to extend this limitation of 8192: 512 for size of parties and size of each party's data vector?

So could I increase LogN to increase 8192 limit for each party's data vector size?
And how could I increase the size of the parties? Such as 5,000 parties? 

BR

**Comment by Pro7ech** [comment]
@macknight Yes, it means that the ring degree is 8192 and that the maximum number of parties that the circuit can support with this parameterization is 512. Also, yes, the number of element per vector is 8192.

I'm sorry that I cannot answer your question about extending the number of parties or the size of the vectors, because it goes out of the scope of the example and is more related to FHE circuit design and parameterization.
