### ISSUE TITLE
collective public key generation

### ISSUE THREAD

**Issue by shuangyichen** [tuneinsight/lattigo#274]
I am using SEAL to implement multiparty homomorphic encryption. I generate collective public key, collective secret key (for checking), and collective rotation key according to the paper and lattigo code. My problem is when I use collective rotation key to rotate a matrix(2*4096), it works for some steps (in my case, 1-1365, 2731-4096 work, 1366-2730 decryption result will not be correct). I use collective secret key to check noise, it is around 140 bits when rotation works but it becomes 0 when not working.  But with the same set of security params, plain HE scheme and rotation key works as normal for all the steps (1~4096). Can you give me some suggestions?   Thanks in advance.

**Comment by Pro7ech** [comment]
Hi @shuangyichen, I will close this issue because the question is not related to the use of the Lattigo library (or about one of its dependencies). If you have trouble using SEAL you can open an issue on their repository, and if you have questions about the paper you are trying to implement, you can contact the authors through the provided contact emails.
