### ISSUE TITLE
rlwe.Evaluator.Expand() works only with ciphertext in NTT domain

### ISSUE THREAD

**Issue by intx4** [tuneinsight/lattigo#313]
It seems that ```func (eval *Evaluator) Expand(ctIn *Ciphertext, logN, logGap int) (ctOut []*Ciphertext)``` works only if the provided ```ctIn``` has been transformed in NTT domain

**Comment by ChristianMct** [comment]
The test at suggests otherwise: [https://github.com/tuneinsight/lattigo/blob/c4214a7669fc2da7d0accd55c1c2401afb2ad532/rlwe/rlwe_test.go#L571](https://github.com/tuneinsight/lattigo/blob/c4214a7669fc2da7d0accd55c1c2401afb2ad532/rlwe/rlwe_test.go#L571)

Can you provide a code snippet reproducing the bug ?
