### ISSUE TITLE
Should I create encryptor by public key or secret key?

### ISSUE THREAD

**Issue by dragonflight2000** [tuneinsight/lattigo#330]
May I know this?
https://github.com/tuneinsight/lattigo/blob/master/ckks/ckks_test.go

Why "testEncryptor" have two ways of creating an encryptor by public key and secret key?
Is there any difference between them? And any difference between the calculation result by encryptors created by public key or secret key respectively?

And I see other testcases all use the encryptor created by secret key. So does it mean encryptor created by public key has any problem, like causing result wrong?

thanks

**Comment by Pro7ech** [comment]
hi @dragonflight2000,

In term of security, there is no difference between an encryptor using the secret-key or the public-key. 

In term of noise, encrypting with the secret-key generate ciphertext with less noise than doing so with the public-key.

Encrypting with the public-key is only tested in `rlwe` because all the other packages use the `rlwe.Encryptor` to encrypt.

**Comment by dragonflight2000** [comment]
> hi @dragonflight2000,
> 
> In term of security, there is no difference between an encryptor using the secret-key or the public-key.
> 
> In term of noise, encrypting with the secret-key generate ciphertext with less noise than doing so with the public-key.
> 
> Encrypting with the public-key is only tested in `rlwe` because all the other packages use the `rlwe.Encryptor` to encrypt.

so is it a better option to use a secret key to create an encryptor rather than to use a public key?

BR

**Comment by Pro7ech** [comment]
Encryption using the public-key is used by entities that do not have access to the secret-key.

It's probably be a typo, but it doesn't the functionalities.

**Comment by dragonflight2000** [comment]
thank you very much
