### ISSUE TITLE
Plaintext-Ciphertext (p-c) multiplication without consuming multiplication level

### ISSUE THREAD

**Issue by PenguinLeee** [tuneinsight/lattigo#362]
Hi, 
In typical CKKS scheme, a message (vector) is interpolated and scaled up to a plaintext polynomial, then the plaintext is encrypted to a ciphertext (in the form of a polynomial pair). 
When we perform typical p-c multiplication, the multiplication level is consumed through rescaling to reduce scale expansion since the plaintext and the ciphertext are all scaled up. 
The scaling-up procedure seems to be non-compulsory for the plaintext during p-c multiplication, which means the p-c multiplication could be performed without consuming multiplication level. 
So the question is, is the thought correct and if correct, is it implemented in lattigo?

**Comment by Pro7ech** [comment]
@PenguinLeee The discretization is necessary step to embed a polynomial of real coefficient in the ring of polynomials with integer coefficients modulo `q`. This is why the real polynomial is multiplied by a scaling factor, to preserve the signal information before the discretization. 

The only way to do a multiplication without consuming a level is to multiply by a Gaussian integer.

This is not a limitation of Lattigo, but a limitation of the CKKS scheme.

However, by using the external product with RGSW ciphertext (and by extension with an RGSW plaintext), you can do a multiplication without consuming a level. However, it also multiplies the error by the plaintext used to multiply with, which is why this scheme is usually used only to multiply with binary values.
