### ISSUE TITLE
Issue on encrypted text multiplication after predefined iteration

### ISSUE THREAD

**Issue by hkanpak21** [tuneinsight/lattigo#408]
We are currently engaged in a split learning project that employs Homomorphic Encryption (HE). A noteworthy issue arises subsequent to performing the multiplication operation involving an encoded plaintext and a ciphertext, specifically after 60 iterations. To facilitate a comprehensive understanding of the matter, I am attaching the primary source file wherein the entire codebase is consolidated.
[OneLevelBatchError.zip](https://github.com/tuneinsight/lattigo/files/12869768/OneLevelBatchError.zip)

It is important to note that, in the event of any difficulties or complications pertaining to the dataset, we have opted for the standard MNIST dataset. However, it is imperative to clarify that the issue in question is fundamentally independent of the dataset itself.

**Comment by Pro7ech** [comment]
Hi @hkanpak21, would it be possible for you to provide a shorter `main.go` that isolates the issue?

Still, I think that it is rather unlikely that this is due to a bug in Lattigo if it happens after 60 iterations. Rather I suspect this is due to some kind of numerical instability, in which case I can only provide general advices. One or several of the following might help you solve your issue:

- Check that the scaling factor remains close to the default scaling factor
- Check that values are distributed within the expected interval
- Check that the imaginary part is not blowing up

**Comment by Pro7ech** [comment]
Closed due to  2w of inactivity
