### ISSUE TITLE
Question:a typo error of comment at line 30 in rgsw/lut/lut.go?   // Interval ]0, 1[ of g(x)  -> // Interval [0, 1] of g(x)

### ISSUE THREAD

**Issue by yiquedexianshi** [tuneinsight/lattigo#410]
a typo error of comment at line 30 in rgsw/lut/lut.go?  
 // Interval ]0, 1[ of g(x)  -> // Interval [0, 1] of g(x)

**Comment by Pro7ech** [comment]
Hi @yiquedexianshi, this is not a typo. Zero is not included in the left-side of the interval because it is already included in the negative interval [-1, 0] and 1 is not included in the right side of the interval because the symmetric interval [-1, 0) U [0] U (0, 1]  divided into 2*(N/2) pieces, one of which includes zero and thus we would need an odd number of pieces to cover everything, but only an even number is available.
