### ISSUE TITLE
Question: Parallelization and Key distribution

### ISSUE THREAD

**Issue by hkanpak21** [tuneinsight/lattigo#447]
Using lattigo v4.1, the issue persists.
I am trying to parallelize a simple neural network that uses lattigo elements. Whenever I try parallelization, the code works fine. However, switching to the encrypted version results in the error code mentioned in the attached file. I was expecting that the code should have worked fine since I am only parallelizing among the input data, where there are no dependencies or possible conflicts.

Added a main.go file that creates the same exact same problem.

[main.txt](https://github.com/tuneinsight/lattigo/files/14595422/main.txt)

Use go run main.go train digits -layers=4 -hidden=128,32 -epochs=10 -rate=.1 to run the code.
Please consider only the first 7 functions (including main) regarding to problem. Rest is trivial, unrelated codes for a simple dense neural network.

**Comment by Pro7ech** [comment]
@hkanpak21 Lattigo is not thread safe, to be able to use concurrency, you need to create a `.ShallowCopy()` of the structs that are used concurrently. 

I will be unable to provide further help because you use the `v4` and I recall that some bugs related to `.ShallowCopy()` not working properly were fixed with the `v5`.

I also strongly suggest to not use `v5@latest` but  v5@4cce9a4` (the latest commit on main).
